[profile.default]
src = 'contracts/src'
test = 'contracts/test'
out = 'contracts/out'
libs = ['contracts/lib']
gas_reports = ["StrategyVault"]

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config